name: dragonfly_navigation
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.1.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  html: ^0.15.4
  http: ^1.2.2
  uuid: ^4.4.2
  dragonfly_css_parser: ^0.0.1
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
