name: website_page
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

  shelf_static: any
dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
