name: dragonfly
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  flutter: ">=3.24.0"
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  path: ^1.9.0
  path_provider: ^2.1.4
  sqlite3: ^2.4.6
  syntax_highlight: ^0.4.0
  window_manager: ^0.4.2
  dragonfly_browservault: ^0.0.1
  dragonfly_navigation: ^0.0.1
  intl: ^0.19.0
  faker: ^2.2.0
  html: ^0.15.4
  url_launcher: ^6.3.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/lobby/
    - assets/styles/
